"""add code embeddings

Revision ID: 1daa707ecb6a
Revises: 82823559d96d
Create Date: 2026-09-06 20:38:10.358106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1daa707ecb6a'
down_revision: Union[str, Sequence[str], None] = '82823559d96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_embeddings_commit_sha'), 'code_embeddings', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_code_embeddings_id'), 'code_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_project_id'), 'code_embeddings', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_user_id'), 'code_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_embeddings_user_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_project_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_commit_sha'), table_name='code_embeddings')
    op.drop_table('code_embeddings')
    # ### end Alembic commands ###
