"""add github installation id

Revision ID: 82823559d96d
Revises: 44370051e6bd
Create Date: 2026-09-05 16:05:01.074444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82823559d96d'
down_revision: Union[str, Sequence[str], None] = '44370051e6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_installation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_github_installation_id'), 'users', ['github_installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_installation_id'), table_name='users')
    op.drop_column('users', 'github_installation_id')
    # ### end Alembic commands ###
