"""add github identity to users

Revision ID: f00899cc2c0b
Revises: 7a18ed2ae8a7
Create Date: 2026-09-05 14:48:48.935063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00899cc2c0b'
down_revision: Union[str, Sequence[str], None] = '7a18ed2ae8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_github_user_id'), 'users', ['github_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_user_id'), table_name='users')
    op.drop_column('users', 'github_user_id')
    # ### end Alembic commands ###
