import {
  AlertCircle,
  ArrowRight,
  ExternalLink,
  GitBranch,
  GitPullRequest,
  Loader2,
  RefreshCw,
  ShieldCheck,
  TestTube2,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getAgentRuns, getProjects } from "../services/api";

type Project = {
  id: number;
  name: string;
  repository_url: string;
  owner_id: number;
};

type AgentRun = {
  id: number;
  project_id: number;
  status: string;
  user_request: string;
  base_branch: string | null;
  agent_branch: string | null;
  pr_number: number | null;
  pr_url: string | null;
  goal: string | null;
  validation_status: string | null;
  test_status: string | null;
  created_at: string;
  completed_at: string | null;
};

function formatDate(value: string) {
  const date = new Date(value.endsWith("Z") ? value : `${value}Z`);

  return date.toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function getProjectName(projects: Project[], projectId: number) {
  return (
    projects.find((project) => project.id === projectId)?.name ??
    "Unknown Project"
  );
}

function getStatusClass(status: string) {
  switch (status.toLowerCase()) {
    case "completed":
    case "approved":
      return "border-emerald-500/20 bg-emerald-500/10 text-emerald-400";

    case "running":
      return "border-yellow-500/20 bg-yellow-500/10 text-yellow-400";

    case "failed":
      return "border-red-500/20 bg-red-500/10 text-red-400";

    default:
      return "border-zinc-700 bg-zinc-800/60 text-zinc-400";
  }
}

function getResultClass(value: string | null) {
  if (value === "passed") {
    return "text-emerald-400";
  }

  if (value === "failed") {
    return "text-red-400";
  }

  return "text-zinc-400";
}

function PullRequests() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [runs, setRuns] = useState<AgentRun[]>([]);

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");

  async function loadPullRequests(isRefresh = false) {
    try {
      if (isRefresh) {
        setRefreshing(true);
      } else {
        setLoading(true);
      }

      setError("");

      const projectData = (await getProjects()) as Project[];
      setProjects(projectData);

      const allRuns: AgentRun[] = [];

      await Promise.all(
        projectData.map(async (project) => {
          try {
            const projectRuns = (await getAgentRuns(
              project.id,
            )) as AgentRun[];

            allRuns.push(...projectRuns);
          } catch {
            // Ignore projects whose runs cannot be loaded.
          }
        }),
      );

      allRuns.sort(
        (a, b) =>
          new Date(b.created_at).getTime() -
          new Date(a.created_at).getTime(),
      );

      setRuns(allRuns);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to load pull requests",
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }

  useEffect(() => {
    loadPullRequests();
  }, []);

  const pullRequests = useMemo(
    () => runs.filter((run) => Boolean(run.pr_url)),
    [runs],
  );

  const successfulPullRequests = useMemo(
    () =>
      pullRequests.filter(
        (run) =>
          run.status === "completed" ||
          run.status === "approved",
      ),
    [pullRequests],
  );

  const failedPullRequests = useMemo(
    () =>
      pullRequests.filter(
        (run) => run.status === "failed",
      ),
    [pullRequests],
  );

  return (
    <div className="mx-auto max-w-7xl space-y-8 px-5 py-8 sm:px-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <GitPullRequest
              size={20}
              className="text-zinc-400"
            />

            <h1 className="text-3xl font-semibold text-white">
              Pull Requests
            </h1>
          </div>

          <p className="mt-2 text-sm text-zinc-500">
            Review pull requests generated by Syntra across your
            projects.
          </p>
        </div>

        <button
          type="button"
          onClick={() => loadPullRequests(true)}
          disabled={loading || refreshing}
          className="flex items-center justify-center gap-2 rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-2.5 text-sm font-medium text-zinc-300 transition hover:bg-zinc-800 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"
        >
          <RefreshCw
            size={15}
            className={refreshing ? "animate-spin" : ""}
          />
          Refresh
        </button>
      </div>

      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          <AlertCircle
            size={18}
            className="mt-0.5 shrink-0"
          />
          <span>{error}</span>
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5">
          <p className="text-sm text-zinc-500">
            Total Pull Requests
          </p>

          <p className="mt-2 text-2xl font-semibold text-white">
            {loading ? "—" : pullRequests.length}
          </p>
        </div>

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5">
          <p className="text-sm text-zinc-500">
            Successful Runs
          </p>

          <p className="mt-2 text-2xl font-semibold text-emerald-400">
            {loading ? "—" : successfulPullRequests.length}
          </p>
        </div>

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5">
          <p className="text-sm text-zinc-500">
            Failed Runs
          </p>

          <p className="mt-2 text-2xl font-semibold text-red-400">
            {loading ? "—" : failedPullRequests.length}
          </p>
        </div>

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5">
          <p className="text-sm text-zinc-500">
            Projects
          </p>

          <p className="mt-2 text-2xl font-semibold text-white">
            {loading ? "—" : projects.length}
          </p>
        </div>
      </div>

      {loading ? (
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-12 text-center">
          <Loader2
            size={24}
            className="mx-auto animate-spin text-zinc-500"
          />

          <p className="mt-3 text-sm text-zinc-500">
            Loading pull requests...
          </p>
        </div>
      ) : pullRequests.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-zinc-800 bg-zinc-900/40 px-6 py-16 text-center">
          <GitPullRequest
            size={30}
            className="mx-auto text-zinc-600"
          />

          <h2 className="mt-4 text-lg font-medium text-white">
            No pull requests yet
          </h2>

          <p className="mx-auto mt-2 max-w-md text-sm text-zinc-500">
            When Syntra successfully creates a pull request,
            it will appear here for review.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {pullRequests.map((run) => (
            <div
              key={run.id}
              className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 transition hover:border-zinc-700"
            >
              <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-full border border-zinc-700 bg-zinc-800/60 px-2.5 py-1 text-xs font-medium text-zinc-400">
                      PR #{run.pr_number ?? "—"}
                    </span>

                    <span
                      className={`rounded-full border px-2.5 py-1 text-xs font-medium ${getStatusClass(
                        run.status,
                      )}`}
                    >
                      {run.status}
                    </span>
                  </div>

                  <h2 className="mt-4 text-base font-medium leading-6 text-white">
                    {run.user_request}
                  </h2>

                  <p className="mt-2 text-xs text-zinc-600">
                    {getProjectName(
                      projects,
                      run.project_id,
                    )}
                    {" • "}
                    Created {formatDate(run.created_at)}
                  </p>
                </div>

                <div className="flex shrink-0 flex-col gap-2 sm:flex-row">
                  <Link
                    to={`/projects/${run.project_id}/runs/${run.id}`}
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-2.5 text-sm font-medium text-zinc-300 transition hover:bg-zinc-800 hover:text-white"
                  >
                    View Run
                    <ArrowRight size={15} />
                  </Link>

                  {run.pr_url && (
                    <a
                      href={run.pr_url}
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-medium text-black transition hover:bg-zinc-200"
                    >
                      GitHub
                      <ExternalLink size={15} />
                    </a>
                  )}
                </div>
              </div>

              {run.goal && (
                <div className="mt-5 rounded-xl border border-zinc-800 bg-zinc-950/50 p-4">
                  <p className="text-[10px] font-medium uppercase tracking-wider text-zinc-600">
                    Agent Goal
                  </p>

                  <p className="mt-2 text-sm leading-6 text-zinc-300">
                    {run.goal}
                  </p>
                </div>
              )}

              <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                <div className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
                  <div className="flex items-center gap-2 text-xs text-zinc-600">
                    <GitBranch size={14} />
                    Base Branch
                  </div>

                  <p className="mt-2 truncate text-sm text-zinc-300">
                    {run.base_branch ?? "—"}
                  </p>
                </div>

                <div className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
                  <div className="flex items-center gap-2 text-xs text-zinc-600">
                    <GitBranch size={14} />
                    Agent Branch
                  </div>

                  <p className="mt-2 truncate text-sm text-zinc-300">
                    {run.agent_branch ?? "—"}
                  </p>
                </div>

                <div className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
                  <div className="flex items-center gap-2 text-xs text-zinc-600">
                    <ShieldCheck size={14} />
                    Validation
                  </div>

                  <p
                    className={`mt-2 text-sm font-medium ${getResultClass(
                      run.validation_status,
                    )}`}
                  >
                    {run.validation_status ??
                      "Not available"}
                  </p>
                </div>

                <div className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
                  <div className="flex items-center gap-2 text-xs text-zinc-600">
                    <TestTube2 size={14} />
                    Tests
                  </div>

                  <p
                    className={`mt-2 text-sm font-medium ${getResultClass(
                      run.test_status,
                    )}`}
                  >
                    {run.test_status ?? "Not available"}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default PullRequests;